# **Growth and Trend Analysis on Philippine Public School Teachers and Students**

A project dedicated to provide an analysis towards the dataset from Kaggle named [Philippine Public School Teachers and Students](https://www.kaggle.com/datasets/franksebastiancayaco/philippine-public-school-teachers-and-students?resource=download).

# Importing libraries and loading the dataset

In [5]:
#import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

#import th the dataset
import kagglehub

# Download latest version
path = kagglehub.dataset_download("franksebastiancayaco/philippine-public-school-teachers-and-students")

Using Colab cache for faster access to the 'philippine-public-school-teachers-and-students' dataset.

In [6]:
#Check the files and folders on the downloaded path
print(os.listdir(path))

['combined_teachers.csv', 'combined_senior_high.csv', 'combined_elementary.csv', 'combined_junior_high.csv']

In [9]:
# Use os.path.join() to load each file from the folder.
teachers_df = pd.read_csv(os.path.join(path, 'combined_teachers.csv'))
senior_high_df = pd.read_csv(os.path.join(path, 'combined_senior_high.csv'))
elementary_df = pd.read_csv(os.path.join(path, 'combined_elementary.csv'))
junior_high_df = pd.read_csv(os.path.join(path, 'combined_junior_high.csv'))

In [14]:
#inspect teachers dataset
teachers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Region        51 non-null     object
 1   SY 2010-2011  34 non-null     float64
 2   SY 2011-2012  34 non-null     float64
 3   SY 2012-2013  34 non-null     float64
 4   SY 2013-2014  34 non-null     float64
 5   SY 2014-2015  34 non-null     float64
 6   SY 2015-2016  34 non-null     float64
 7   SY 2016-2017  51 non-null     int64
 8   SY 2017-2018  51 non-null     int64
 9   SY 2018-2019  51 non-null     int64
 10  SY 2019-2020  51 non-null     int64
 11  SY 2020-2021  51 non-null     int64
 12  Level         51 non-null     object
dtypes: float64(6), int64(5), object(2)
memory usage: 5.3+ KB

In [22]:
teachers_df.head(5)

,Region,SY 2010-2011,SY 2011-2012,SY 2012-2013,SY 2013-2014,SY 2014-2015,SY 2015-2016,SY 2016-2017,SY 2017-2018,SY 2018-2019,SY 2019-2020,SY 2020-2021,Level
0,Region I - Ilocos Region,21604.0,21790.0,22235.0,22779.0,23071.0,24138.0,24237,24768,25737,25955,26699,Elementary
1,Region II - Cagayan Valley,14728.0,14521.0,15284.0,16038.0,16435.0,17857.0,18098,18420,19289,19546,20534,Elementary
2,Region III - Central Luzon,34952.0,35418.0,36417.0,38774.0,39972.0,43501.0,43342,44493,48160,48812,49911,Elementary
3,Region IV-A - CALABARZON,37190.0,37501.0,39513.0,43299.0,45219.0,49264.0,49530,51167,55041,57348,60421,Elementary
4,Region IV-B - MIMAROPA,12900.0,13215.0,13622.0,14826.0,15516.0,17279.0,16982,17394,17946,18509,19277,Elementary

In [11]:
#inspect senior high school students dataset
senior_high_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Region       1224 non-null   object
 1   School Year  1224 non-null   object
 2   Grade Level  1224 non-null   object
 3   Students     1224 non-null   float64
dtypes: float64(1), object(3)
memory usage: 38.4+ KB

In [40]:
senior_high_df.head(5)

                       Region School Year     Grade Level  Students
0    Region I - Ilocos Region   2016-2017  Grade 11 (TVL)   24406.0
1  Region II - Cagayan Valley   2016-2017  Grade 11 (TVL)   11284.0
2  Region III - Central Luzon   2016-2017  Grade 11 (TVL)   36297.0
3    Region IV-A - CALABARZON   2016-2017  Grade 11 (TVL)   36577.0
4      Region IV-B - MIMAROPA   2016-2017  Grade 11 (TVL)   12602.0

In [12]:
#inspect junior high school students dataset
junior_high_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Region       1122 non-null   object
 1   School Year  1122 non-null   object
 2   Grade Level  1122 non-null   object
 3   Students     850 non-null    float64
dtypes: float64(1), object(3)
memory usage: 35.2+ KB

In [17]:
junior_high_df.head(5)

                       Region School Year Grade Level  Students
0    Region I - Ilocos Region   2010-2011     Grade 7   84273.0
1  Region II - Cagayan Valley   2010-2011     Grade 7   54156.0
2  Region III - Central Luzon   2010-2011     Grade 7  171749.0
3    Region IV-A - CALABARZON   2010-2011     Grade 7  205849.0
4      Region IV-B - MIMAROPA   2010-2011     Grade 7   56084.0

In [29]:
#inspect elementary school students dataset
elementary_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1496 entries, 0 to 1495
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Region       1496 non-null   object
 1   School Year  1496 non-null   object
 2   Grade Level  1496 non-null   object
 3   Students     1428 non-null   float64
dtypes: float64(1), object(3)
memory usage: 46.9+ KB

In [34]:
elementary_df.head(15)

,Region,School Year,Grade Level,Students
0,Region I - Ilocos Region,2010-2011,Kindergarten,84553.0
1,Region II - Cagayan Valley,2010-2011,Kindergarten,27079.0
2,Region III - Central Luzon,2010-2011,Kindergarten,141901.0
3,Region IV-A - CALABARZON,2010-2011,Kindergarten,135149.0
4,Region IV-B - MIMAROPA,2010-2011,Kindergarten,47289.0
5,Region V - Bicol Region,2010-2011,Kindergarten,106282.0
6,Region VI - Western Visayas,2010-2011,Kindergarten,88707.0
7,Region VII - Central Visayas,2010-2011,Kindergarten,120553.0
8,Region VIII - Eastern Visayas,2010-2011,Kindergarten,67173.0
9,Region IX - Zamboanga Peninsula,2010-2011,Kindergarten,60672.0
10,Region X - Northern Mindanao,2010-2011,Kindergarten,57102.0
11,Region XI - Davao Region,2010-2011,Kindergarten,42417.0
12,Region XII - Soccsksargen,2010-2011,Kindergarten,61520.0
13,CARAGA - CARAGA,2010-2011,Kindergarten,48737.0
14,BARMM - Bangsamoro Autonomous Region in Muslim...,2010-2011,Kindergarten,55221.0

# Data Reshaping/ Transformation

Upon examining/inspecting each dataset, we've discovered that the teachers_df having 13 columns is much more than the students' datasets which only have 4. The info is listed again below for reference.

In [49]:
# Merge the students and teachers DataFrames on the common columns
# Using an 'outer' merge to ensure we don't lose any data
final_df = pd.merge(students_df, melted_teachers_df, on=['Region', 'School Year', 'School Level'], how='outer')

# Now check the final merged DataFrame
print(final_df.info())
print(final_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4403 entries, 0 to 4402
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              4403 non-null   object
 1   School Year         4403 non-null   object
 2   Students            3502 non-null   float64
 3   School Level        4403 non-null   object
 4   Number of Teachers  459 non-null    float64
dtypes: float64(2), object(3)
memory usage: 172.1+ KB
None
                                              Region School Year  Students  \
0  BARMM - Bangsamoro Autonomous Region in Muslim...   2010-2011   55221.0
1  BARMM - Bangsamoro Autonomous Region in Muslim...   2010-2011  199242.0
2  BARMM - Bangsamoro Autonomous Region in Muslim...   2010-2011  152075.0
3  BARMM - Bangsamoro Autonomous Region in Muslim...   2010-2011  122489.0
4  BARMM - Bangsamoro Autonomous Region in Muslim...   2010-2011   95431.0

  School Level  Number of Teachers
0   Elementary                 NaN
1   Elementary                 NaN
2   Elementary                 NaN
3   Elementary                 NaN
4   Elementary                 NaN

As a solution, Pandas' melt() function will be utilized to convert the
 ```teachers_df ```
 from wide format into along format, matching the structure of the students' data.

In [41]:
#use melt() to reshape the data frame
melted_teachers_df = teachers_df.melt(
                    id_vars=['Region', 'Level'], value_vars=['SY 2010-2011', 'SY 2011-2012', 'SY 2012-2013', 'SY 2013-2014',
                                                             'SY 2014-2015', 'SY 2015-2016', 'SY 2016-2017', 'SY 2017-2018',
                                                             'SY 2018-2019', 'SY 2019-2020', 'SY 2020-2021'],
                    var_name='School Year',
                    value_name='Number of Teachers'
)
melted_teachers_df.head(5)

                       Region       Level   School Year  Number of Teachers
0    Region I - Ilocos Region  Elementary  SY 2010-2011             21604.0
1  Region II - Cagayan Valley  Elementary  SY 2010-2011             14728.0
2  Region III - Central Luzon  Elementary  SY 2010-2011             34952.0
3    Region IV-A - CALABARZON  Elementary  SY 2010-2011             37190.0
4      Region IV-B - MIMAROPA  Elementary  SY 2010-2011             12900.0

For the last step, the  ```Grade Level``` column for students datasets are specified compared to the teacher's data wherein the level are generalized to elementary, junior high school, and others. So we need to categorize the students too in a general manner.

In [42]:
# Add a 'School Level' column to the elementary student DataFrame
elementary_df['School Level'] = 'Elementary'

# Add a 'School Level' column to the junior high student DataFrame
junior_high_df['School Level'] = 'Junior High'

# Add a 'School Level' column to the senior high student DataFrame
senior_high_df['School Level'] = 'Senior High'

In [43]:
# Combine the students' datasets
student_dfs = [elementary_df, junior_high_df, senior_high_df]

# Use pd.concat() to stack them vertically
students_df = pd.concat(student_dfs, ignore_index=True)

# The axis=1 argument tells pandas to drop a column (not a row)
# The inplace=True argument modifies the dataframe directly
students_df.drop('Grade Level', axis=1, inplace=True)

# Inspect the data
students_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3842 entries, 0 to 3841
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Region        3842 non-null   object
 1   School Year   3842 non-null   object
 2   Students      3502 non-null   float64
 3   School Level  3842 non-null   object
dtypes: float64(1), object(3)
memory usage: 120.2+ KB

In [44]:
students_df.head(5)

                       Region School Year  Students School Level
0    Region I - Ilocos Region   2010-2011   84553.0   Elementary
1  Region II - Cagayan Valley   2010-2011   27079.0   Elementary
2  Region III - Central Luzon   2010-2011  141901.0   Elementary
3    Region IV-A - CALABARZON   2010-2011  135149.0   Elementary
4      Region IV-B - MIMAROPA   2010-2011   47289.0   Elementary

Merge the students_df with melted_teachers_df

In [46]:
# Rename the 'Level' column in the melted teachers DataFrame to match the students DataFrame
melted_teachers_df.rename(columns={'Level': 'School Level'}, inplace=True)

melted_teachers_df.head(5)

                       Region School Level   School Year  Number of Teachers
0    Region I - Ilocos Region   Elementary  SY 2010-2011             21604.0
1  Region II - Cagayan Valley   Elementary  SY 2010-2011             14728.0
2  Region III - Central Luzon   Elementary  SY 2010-2011             34952.0
3    Region IV-A - CALABARZON   Elementary  SY 2010-2011             37190.0
4      Region IV-B - MIMAROPA   Elementary  SY 2010-2011             12900.0

In [47]:
# Merge the students and teachers DataFrames on the common columns
# Using an 'outer' merge to ensure we don't lose any data
final_df = pd.merge(students_df, melted_teachers_df, on=['Region', 'School Year', 'School Level'], how='outer')

# Now check the final merged DataFrame
print(final_df.info())
print(final_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4403 entries, 0 to 4402
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              4403 non-null   object
 1   School Year         4403 non-null   object
 2   Students            3502 non-null   float64
 3   School Level        4403 non-null   object
 4   Number of Teachers  459 non-null    float64
dtypes: float64(2), object(3)
memory usage: 172.1+ KB
None
                                              Region School Year  Students  \
0  BARMM - Bangsamoro Autonomous Region in Muslim...   2010-2011   55221.0
1  BARMM - Bangsamoro Autonomous Region in Muslim...   2010-2011  199242.0
2  BARMM - Bangsamoro Autonomous Region in Muslim...   2010-2011  152075.0
3  BARMM - Bangsamoro Autonomous Region in Muslim...   2010-2011  122489.0
4  BARMM - Bangsamoro Autonomous Region in Muslim...   2010-2011   95431.0

  School Level  Number of Teachers
0   Elementary                 NaN
1   Elementary                 NaN
2   Elementary                 NaN
3   Elementary                 NaN
4   Elementary                 NaN

In [50]:
final_df.head(5)

,Region,School Year,Students,School Level,Number of Teachers
0,BARMM - Bangsamoro Autonomous Region in Muslim...,2010-2011,55221.0,Elementary,NaN
1,BARMM - Bangsamoro Autonomous Region in Muslim...,2010-2011,199242.0,Elementary,NaN
2,BARMM - Bangsamoro Autonomous Region in Muslim...,2010-2011,152075.0,Elementary,NaN
3,BARMM - Bangsamoro Autonomous Region in Muslim...,2010-2011,122489.0,Elementary,NaN
4,BARMM - Bangsamoro Autonomous Region in Muslim...,2010-2011,95431.0,Elementary,NaN

In [51]:
# Fill NaN values in 'Students' and 'Number of Teachers' columns with 0
final_df['Students'].fillna(0, inplace=True)
final_df['Number of Teachers'].fillna(0, inplace=True)

# Check the result to confirm there are no more NaNs in these columns
print(final_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4403 entries, 0 to 4402
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              4403 non-null   object
 1   School Year         4403 non-null   object
 2   Students            4403 non-null   float64
 3   School Level        4403 non-null   object
 4   Number of Teachers  4403 non-null   float64
dtypes: float64(2), object(3)
memory usage: 172.1+ KB
None

/tmp/ipython-input-54734542.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df['Students'].fillna(0, inplace=True)
/tmp/ipython-input-54734542.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df['Number of Teachers'].fillna(0, inplace=True)

# **Analysis Phase**

Since the data is cleaned and preprocessed, it's fitting to begin the analysis.

In [52]:
#Calculate the student-teacher ratio
final_df['Teachers_per_Student_Ratio'] = final_df['Number of Teachers'] / final_df['Students']

In [55]:
# Group by School Year and School Level and calculate the sums
summary_df = final_df.groupby(['School Year', 'School Level']).agg(
    Total_Students=('Students', 'sum'),
    Total_Teachers=('Number of Teachers', 'sum')
).reset_index()

# Calculate the ratio on this summary data as well
summary_df['Total_Teachers_per_Student'] = summary_df['Total_Teachers'] / summary_df['Total_Students']

In [62]:
summary_df.head(10)

,School Year,School Level,Total_Students,Total_Teachers,Total_Teachers_per_Student
0,2010-2011,Elementary,14238772.0,0.0,0.0
1,2010-2011,Junior High,5530370.0,0.0,0.0
2,2011-2012,Elementary,14898142.0,0.0,0.0
3,2011-2012,Junior High,5576065.0,0.0,0.0
4,2012-2013,Elementary,15032994.0,0.0,0.0
5,2012-2013,Junior High,5641898.0,0.0,0.0
6,2013-2014,Elementary,15111655.0,0.0,0.0
7,2013-2014,Junior High,5772578.0,0.0,0.0
8,2014-2015,Elementary,15114208.0,0.0,0.0
9,2014-2015,Junior High,5928042.0,0.0,0.0

In [63]:
# Replace all 'inf' values with 0
final_df.replace([np.inf, -np.inf], 0, inplace=True)

# Replace any remaining NaN values with 0
final_df['Teachers_per_Student_Ratio'].fillna(0, inplace=True)

# Check the result
print(final_df.describe())

            Students  Number of Teachers  Teachers_per_Student_Ratio
count    4403.000000         4403.000000                      4403.0
mean    53393.256643         1704.290030                         0.0
std     67083.869867         6326.011412                         0.0
min         0.000000            0.000000                         0.0
25%        30.000000            0.000000                         0.0
50%     16626.000000            0.000000                         0.0
75%     93258.500000            0.000000                         0.0
max    329623.000000        60421.000000                         0.0

/tmp/ipython-input-1686433889.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df['Teachers_per_Student_Ratio'].fillna(0, inplace=True)

Visualize the computation

In [57]:
plt.figure(figsize=(10,8))
sns.lineplot(data=summary_df, x='School Year', y='Students', hue='School Level')

ValueError: Could not interpret value `Students` for `y`. An entry with this name does not appear in `data`.